USE ECOMM_STORE;

-- NÃO USAR *
SELECT * FROM PRODUCTS_3;

SELECT 
	PRODUCT_ID, PRODUCT_NAME, QUANTITY -- SELECIONAR SOMENTE O NECESSÁRIO
FROM 
	PRODUCTS_3 -- JOINS
WHERE 
	QUANTITY < 25 -- USAR COLUNAS ID
ORDER BY PRODUCT_NAME; -- PODE SER DEMORADO DEPENDENDO DO BUFFER

SELECT NOW(), DATABASE();
 