-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ECOMM_STORE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ECOMM_STORE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ECOMM_STORE` DEFAULT CHARACTER SET utf8 ;
USE `ECOMM_STORE` ;

-- -----------------------------------------------------
-- Table `ECOMM_STORE`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECOMM_STORE`.`CUSTOMER` (
  `CUSTOMER_ID` INT NOT NULL,
  `FIRST_NAME` VARCHAR(100) NOT NULL,
  `LAST NAME` VARCHAR(100) NOT NULL,
  `ADDRESS` VARCHAR(200) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `COUNTRY` VARCHAR(45) NOT NULL,
  `ZIPCODE` VARCHAR(45) NOT NULL,
  `PHONE_NUMBER` INT(15) NOT NULL,
  `EMAIL_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  UNIQUE INDEX `EMAIL_ID_UNIQUE` (`EMAIL_ID` ASC) VISIBLE,
  UNIQUE INDEX `PHONE_NUMBER_UNIQUE` (`PHONE_NUMBER` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECOMM_STORE`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECOMM_STORE`.`PRODUCTS` (
  `PRODUCT_ID` INT NOT NULL,
  `PRODUCT_NAME` VARCHAR(200) NOT NULL,
  `PRODUCT_TYPE` VARCHAR(45) NOT NULL,
  `PRICE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  UNIQUE INDEX `PRODUCT_NAME_UNIQUE` (`PRODUCT_NAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECOMM_STORE`.`PAYMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECOMM_STORE`.`PAYMENTS` (
  `PAYMENT_ID` INT NOT NULL,
  `CUSTOMER_ID` INT NOT NULL,
  `PAYMENT_TYPE` VARCHAR(45) NOT NULL,
  `CC_NUMBER` INT NOT NULL,
  `EXPIRATION_DATE` DATE NOT NULL,
  `CVV` INT NOT NULL,
  `EMAIL_ID` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`PAYMENT_ID`),
  INDEX `CUSTOMERID_FK1_idx` (`CUSTOMER_ID` ASC) VISIBLE,
  CONSTRAINT `CUSTOMERID_FK1`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `ECOMM_STORE`.`CUSTOMER` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECOMM_STORE`.`ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECOMM_STORE`.`ORDERS` (
  `ORDER_ID` INT NOT NULL,
  `DEVICE` VARCHAR(45) NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `CUSTOMER_ID` INT NOT NULL,
  `PAYMENT_ID` INT NOT NULL,
  `SHIPPING_ADRESS` VARCHAR(100) NOT NULL,
  `SHIPPING_CYTY` VARCHAR(100) NOT NULL,
  `SHIPPING_STATE` VARCHAR(2) NOT NULL,
  `SHIPPING_COUNTRY` VARCHAR(45) NOT NULL,
  `DELIVERED` CHAR(1) NOT NULL,
  PRIMARY KEY (`ORDER_ID`),
  INDEX `PRODUCTID_FK_idx` (`PRODUCT_ID` ASC) VISIBLE,
  INDEX `CUSTOMERID_FK2_idx` (`CUSTOMER_ID` ASC) VISIBLE,
  INDEX `PAYMENTID_FK_idx` (`PAYMENT_ID` ASC) VISIBLE,
  CONSTRAINT `PRODUCTID_FK`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `ECOMM_STORE`.`PRODUCTS` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CUSTOMERID_FK2`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `ECOMM_STORE`.`CUSTOMER` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PAYMENTID_FK`
    FOREIGN KEY (`PAYMENT_ID`)
    REFERENCES `ECOMM_STORE`.`PAYMENTS` (`PAYMENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
