USE ECOMM_STORE;

DROP TABLE PRODUCTS_1;

CREATE TABLE `PRODUCTS_1` (
    `PRODUCT_ID` INT NOT NULL AUTO_INCREMENT,
    `PRODUCT_NAME` VARCHAR(200) NOT NULL,
    `PRODUCT_TYPE` VARCHAR(45) NOT NULL,
    `PRICE` DECIMAL(10 , 2 ) NOT NULL,
    `QUANTITY` INT NOT NULL DEFAULT 0,
    PRIMARY KEY (`PRODUCT_ID`),
    UNIQUE KEY `PRODUCT_NAME_UNIQUE` (`PRODUCT_NAME`)
)  ENGINE=INNODB;

SELECT 
    *
FROM
    PRODUCTS_1
